export type Gender = "Men" | "Ladies" | "Couple" | "Unisex";

export interface Product {
  id: string;
  slug: string;
  sku: string;
  brand: string;
  brandSlug: string;
  name: string;
  price: number;
  compareAt?: number;
  image: string;
  badge?: string;
  gender: Gender;
  category: string;
  strap: string;
  dial: string;
  movement: string;
  caseSize: string;
  waterResistance: string;
  description: string;
  rating: number;
  reviews: number;
  dateAdded: number;
}

export const products: Product[] = [
  // ---- Seiko (3) ----
  {
    id: "seiko-prospex-save-the-ocean",
    slug: "seiko-prospex-save-the-ocean-spb297",
    sku: "SPB297J1",
    brand: "Seiko",
    brandSlug: "seiko",
    name: "Prospex Save the Ocean Automatic Diver | SPB297",
    price: 89000,
    compareAt: 96000,
    image: "/images/products/product-06.jpg",
    badge: "NEW",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "41.3mm",
    waterResistance: "20 ATM",
    description:
      "Inspired by the glaciers of Antarctica, the Save the Ocean series pairs an ice-blue textured dial with Seiko's reliable automatic movement and 200m water resistance.",
    rating: 4.8,
    reviews: 22,
    dateAdded: 100,
  },
  {
    id: "seiko-5-sports-field",
    slug: "seiko-5-sports-field-watch-srpd",
    sku: "SRPD55K1",
    brand: "Seiko",
    brandSlug: "seiko",
    name: "5 Sports Field Watch | SRPD55",
    price: 45000,
    compareAt: 51000,
    image: "/images/products/img-14.jpg",
    gender: "Men",
    category: "Sports",
    strap: "Steel",
    dial: "Black",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "10 ATM",
    description:
      "The 5 Sports badge carries a 4R36 automatic movement, day-date window and a rugged case that moves from desk to weekend without missing a second.",
    rating: 4.7,
    reviews: 34,
    dateAdded: 95,
  },
  {
    id: "seiko-presage-cocktail-time",
    slug: "seiko-presage-cocktail-time-srpb43",
    sku: "SRPB43J1",
    brand: "Seiko",
    brandSlug: "seiko",
    name: "Presage Cocktail Time Blue | SRPB43",
    price: 58500,
    compareAt: 64000,
    image: "/images/products/img-15.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "40.5mm",
    waterResistance: "5 ATM",
    description:
      "A sunburst 'cocktail' dial inspired by the gin fizz, framed in a polished case. Presage is Seiko's love letter to classic dress-watch design.",
    rating: 4.8,
    reviews: 19,
    dateAdded: 90,
  },
  // ---- Casio (4) ----
  {
    id: "casio-gshock-mudmaster",
    slug: "casio-g-shock-g-land-mudmaster-gg-1000-1adr",
    sku: "GG-1000-1ADR",
    brand: "Casio",
    brandSlug: "casio",
    name: "G-Shock G-Land Mudmaster | GG-1000-1ADR",
    price: 48500,
    compareAt: 53500,
    image: "/images/products/product-02.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Resin",
    dial: "Black",
    movement: "Quartz",
    caseSize: "51.9mm",
    waterResistance: "20 ATM",
    description:
      "Built for the harshest terrain, the Mudmaster layers dual-layer construction, mud resistance and triple-sensor technology inside a commanding G-Shock silhouette.",
    rating: 4.8,
    reviews: 41,
    dateAdded: 85,
  },
  {
    id: "casio-edifice-efs-s570",
    slug: "casio-edifice-efs-s570",
    sku: "EFS-S570-1AV",
    brand: "Casio",
    brandSlug: "casio",
    name: "Edifice EFS-S570 Chronograph Solar",
    price: 21500,
    compareAt: 24500,
    image: "/images/products/product-04.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Steel",
    dial: "Black",
    movement: "Solar",
    caseSize: "43mm",
    waterResistance: "10 ATM",
    description:
      "Race-inspired styling meets smart solar power. The Edifice EFS-S570 pairs a tachymeter chronograph with a sapphire crystal and Tough Solar movement.",
    rating: 4.7,
    reviews: 12,
    dateAdded: 80,
  },
  {
    id: "casio-vintage-data-bank",
    slug: "casio-vintage-data-bank-db-360-1adf",
    sku: "DB-360-1ADF",
    brand: "Casio",
    brandSlug: "casio",
    name: "Vintage Data Bank Steel | DB-360-1ADF",
    price: 4750,
    compareAt: 5750,
    image: "/images/products/product-08.jpg",
    badge: "SALE",
    gender: "Unisex",
    category: "Digital",
    strap: "Steel",
    dial: "Black",
    movement: "Quartz",
    caseSize: "38mm",
    waterResistance: "3 ATM",
    description:
      "Retro computing charm in a stainless case. The legendary Data Bank brings digital keys, a 1980s LCD display and serious nostalgia to any collection.",
    rating: 4.7,
    reviews: 55,
    dateAdded: 75,
  },
  {
    id: "casio-pro-trek-prw",
    slug: "casio-pro-trek-prw-6900yl-5dr",
    sku: "PRW-6900YL-5DR",
    brand: "Casio",
    brandSlug: "casio",
    name: "Pro-Trek Solar Triple Sensor | PRW-6900YL-5DR",
    price: 67500,
    compareAt: 72500,
    image: "/images/products/product-11.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Leather",
    dial: "Green",
    movement: "Solar",
    caseSize: "47mm",
    waterResistance: "20 ATM",
    description:
      "An adventure companion with a green dial, brown leather strap and every sensor a trek could demand — all powered by light alone.",
    rating: 4.8,
    reviews: 11,
    dateAdded: 70,
  },
  // ---- Citizen (3) ----
  {
    id: "citizen-promaster-diver",
    slug: "citizen-promaster-eco-drive-diver",
    sku: "BN0168-55X",
    brand: "Citizen",
    brandSlug: "citizen",
    name: "Promaster Eco-Drive Diver 200m",
    price: 54000,
    compareAt: 59000,
    image: "/images/products/product-13.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Blue",
    movement: "Solar",
    caseSize: "44mm",
    waterResistance: "20 ATM",
    description:
      "The professional's choice. Eco-Drive runs forever on light, while 200m of water resistance and a luminous dial take it to serious depth.",
    rating: 4.8,
    reviews: 19,
    dateAdded: 65,
  },
  {
    id: "citizen-eco-drive-chandler",
    slug: "citizen-eco-drive-chandler-bm8240",
    sku: "BM8240-03E",
    brand: "Citizen",
    brandSlug: "citizen",
    name: "Eco-Drive Chandler | BM8240-03E",
    price: 27500,
    compareAt: 31000,
    image: "/images/products/img-16.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "White",
    movement: "Solar",
    caseSize: "40mm",
    waterResistance: "5 ATM",
    description:
      "A clean silver dial on a rich brown leather strap. The Chandler proves an Eco-Drive can be handsome at the office and never need a battery.",
    rating: 4.6,
    reviews: 27,
    dateAdded: 60,
  },
  {
    id: "citizen-corso-eco-drive",
    slug: "citizen-corso-eco-drive-bu2020",
    sku: "BU2020-57A",
    brand: "Citizen",
    brandSlug: "citizen",
    name: "Corso Eco-Drive | BU2020-57A",
    price: 31500,
    compareAt: 35000,
    image: "/images/products/img-17.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "White",
    movement: "Solar",
    caseSize: "40mm",
    waterResistance: "5 ATM",
    description:
      "Polished link bracelet, silver dial, sapphire glass. The Corso is Citizen's modern answer to the classic everyday dress watch.",
    rating: 4.6,
    reviews: 15,
    dateAdded: 55,
  },
  // ---- Orient (3) ----
  {
    id: "orient-bambino-v7",
    slug: "orient-bambino-version-7-cream",
    sku: "RA-AC0M04Y10B",
    brand: "Orient",
    brandSlug: "orient",
    name: "Bambino Version 7 Cream | RA-AC0M04",
    price: 38500,
    compareAt: 43000,
    image: "/images/products/img-19.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "White",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "3 ATM",
    description:
      "The Bambino needs no introduction — a domed crystal, cream dial and in-house automatic movement make it the most famous affordable dress watch on earth.",
    rating: 4.8,
    reviews: 47,
    dateAdded: 50,
  },
  {
    id: "orient-kamasu-red",
    slug: "orient-kamasu-red-diver-rav-kb0003",
    sku: "RA-AA0003R19B",
    brand: "Orient",
    brandSlug: "orient",
    name: "Kamasu Red Diver | RA-AA0003R19B",
    price: 44500,
    compareAt: 49000,
    image: "/images/products/img-20.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Red",
    movement: "Automatic",
    caseSize: "41mm",
    waterResistance: "20 ATM",
    description:
      "A sapphire-crystal diver with a blazing red dial and Orient's own F6922 automatic movement. Serious dive specs at a friendly price.",
    rating: 4.7,
    reviews: 23,
    dateAdded: 45,
  },
  {
    id: "orient-mako-ii",
    slug: "orient-mako-ii-pepsi-diver",
    sku: "RA-AA0811R19B",
    brand: "Orient",
    brandSlug: "orient",
    name: "Mako II Pepsi Diver | RA-AA0811R19B",
    price: 37500,
    compareAt: 41000,
    image: "/images/products/img-21.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "41mm",
    waterResistance: "20 ATM",
    description:
      "The Mako II brings the beloved 'Pepsi' bezel to Orient's classic entry diver — a bright, reliable automatic you'll never want to take off.",
    rating: 4.7,
    reviews: 31,
    dateAdded: 40,
  },
  // ---- Tissot (3) ----
  {
    id: "tissot-prx-powermatic",
    slug: "tissot-prx-powermatic-80-t-gold",
    sku: "T137.407.21.031.00",
    brand: "Tissot",
    brandSlug: "tissot",
    name: "PRX Powermatic 80 White Dial | T137.407.21.031.00",
    price: 93500,
    compareAt: 99000,
    image: "/images/products/product-03.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "White",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "10 ATM",
    description:
      "The legendary 1970s integrated bracelet design, reborn with a Powermatic 80 automatic movement offering an 80-hour power reserve. A modern classic.",
    rating: 5.0,
    reviews: 16,
    dateAdded: 35,
  },
  {
    id: "tissot-le-locle",
    slug: "tissot-le-locle-automatic",
    sku: "T006.407.11.033.00",
    brand: "Tissot",
    brandSlug: "tissot",
    name: "Le Locle Automatic | T006.407.11.033.00",
    price: 65500,
    compareAt: 71000,
    image: "/images/products/img-22.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "White",
    movement: "Automatic",
    caseSize: "39.3mm",
    waterResistance: "3 ATM",
    description:
      "Named after the birthplace of Swiss watchmaking, the Le Locle carries an ETA automatic movement and a guilloché dial under a sapphire crystal.",
    rating: 4.7,
    reviews: 12,
    dateAdded: 30,
  },
  {
    id: "tissot-gentleman",
    slug: "tissot-gentleman-powermatic-80",
    sku: "T127.407.11.041.00",
    brand: "Tissot",
    brandSlug: "tissot",
    name: "Gentleman Powermatic 80 | T127.407.11.041.00",
    price: 73500,
    compareAt: 79000,
    image: "/images/products/img-23.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "Black",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "10 ATM",
    description:
      "A versatile go-anywhere automatic with a black dial, 80-hour power reserve and 316L steel — the watch a gentleman reaches for first.",
    rating: 4.8,
    reviews: 9,
    dateAdded: 25,
  },
  // ---- Longines (3) ----
  {
    id: "longines-spirit-zulu",
    slug: "longines-spirit-zulu-time-gmt-l38024936",
    sku: "L3.802.4.96.6",
    brand: "Longines",
    brandSlug: "longines",
    name: "Spirit Zulu Time GMT Automatic | L38024936",
    price: 415000,
    compareAt: 430000,
    image: "/images/products/product-10.jpg",
    badge: "PREMIUM",
    gender: "Men",
    category: "GMT",
    strap: "Steel",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "42mm",
    waterResistance: "10 ATM",
    description:
      "Longines' modern aviation legend with a true GMT function. An Arabic-indexed blue dial, bi-directional ceramic bezel and an automatic movement with 72h reserve.",
    rating: 5.0,
    reviews: 7,
    dateAdded: 20,
  },
  {
    id: "longines-hydroconquest",
    slug: "longines-hydroconquest-green",
    sku: "L3.841.4.56.6",
    brand: "Longines",
    brandSlug: "longines",
    name: "HydroConquest Green | L3.841.4.56.6",
    price: 285000,
    compareAt: 295000,
    image: "/images/products/img-24.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Green",
    movement: "Automatic",
    caseSize: "41mm",
    waterResistance: "30 ATM",
    description:
      "A 300m professional diver with a deep-green dial and ceramic bezel — Longines' most wearable sports watch meets serious underwater credentials.",
    rating: 4.9,
    reviews: 8,
    dateAdded: 15,
  },
  {
    id: "longines-master-collection",
    slug: "longines-master-collection-automatic",
    sku: "L2.793.4.78.6",
    brand: "Longines",
    brandSlug: "longines",
    name: "Master Collection Automatic | L2.793.4.78.6",
    price: 335000,
    compareAt: 345000,
    image: "/images/products/img-25.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "White",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "3 ATM",
    description:
      "A silvered dial, blued steel hands and a column-wheel chronograph movement. The Master Collection is Longines at its most elegant.",
    rating: 4.9,
    reviews: 6,
    dateAdded: 10,
  },
  // ---- Rado (3) ----
  {
    id: "rado-true-thinline",
    slug: "rado-true-thinline-platinum",
    sku: "R27059152",
    brand: "Rado",
    brandSlug: "rado",
    name: "True Thinline Platinum | R27059152",
    price: 245000,
    compareAt: 255000,
    image: "/images/products/img-26.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Ceramic",
    dial: "White",
    movement: "Quartz",
    caseSize: "40mm",
    waterResistance: "5 ATM",
    description:
      "The world of the True Thinline is feather-light and scratch-proof — high-tech ceramic, a monochrome dial and a slim profile that disappears on the wrist.",
    rating: 4.7,
    reviews: 5,
    dateAdded: 9,
  },
  {
    id: "rado-captain-cook",
    slug: "rado-captain-cook-green",
    sku: "R32505315",
    brand: "Rado",
    brandSlug: "rado",
    name: "Captain Cook Green | R32505315",
    price: 315000,
    compareAt: 325000,
    image: "/images/products/img-27.jpg",
    gender: "Men",
    category: "Diving",
    strap: "Steel",
    dial: "Green",
    movement: "Automatic",
    caseSize: "42mm",
    waterResistance: "20 ATM",
    description:
      "A retro-future diver with a green dial, boxed sapphire crystal and rotating bezel — the Captain Cook is Rado's most beloved modern classic.",
    rating: 4.8,
    reviews: 7,
    dateAdded: 8,
  },
  {
    id: "rado-centrix",
    slug: "rado-centrix-automatic",
    sku: "R30941162",
    brand: "Rado",
    brandSlug: "rado",
    name: "Centrix Automatic | R30941162",
    price: 195000,
    compareAt: 205000,
    image: "/images/products/img-28.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "White",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "5 ATM",
    description:
      "Fluid ceramic curves and a silvered dial. The Centrix wraps Swiss automatic engineering in Rado's signature touch — warm, rounded, unmistakably ceramic.",
    rating: 4.7,
    reviews: 4,
    dateAdded: 7,
  },
  // ---- Hamilton (3) ----
  {
    id: "hamilton-khaki-field",
    slug: "hamilton-khaki-field-auto-38",
    sku: "H70455533",
    brand: "Hamilton",
    brandSlug: "hamilton",
    name: "Khaki Field Auto 38 | H70455533",
    price: 78500,
    compareAt: 84500,
    image: "/images/products/img-29.jpg",
    gender: "Men",
    category: "Sports",
    strap: "Leather",
    dial: "Black",
    movement: "Automatic",
    caseSize: "38mm",
    waterResistance: "10 ATM",
    description:
      "Born from military field watches, the Khaki Field pairs a matte black dial with a Hamilton automatic movement. Rugged, legible, forever in style.",
    rating: 4.8,
    reviews: 26,
    dateAdded: 6,
  },
  {
    id: "hamilton-jazzmaster",
    slug: "hamilton-jazzmaster-day-date",
    sku: "H32505511",
    brand: "Hamilton",
    brandSlug: "hamilton",
    name: "Jazzmaster Day Date | H32505511",
    price: 94500,
    compareAt: 99500,
    image: "/images/products/img-30.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "Black",
    movement: "Automatic",
    caseSize: "40mm",
    waterResistance: "5 ATM",
    description:
      "The Jazzmaster strikes a chord between dress and sport — a sunburst dial, day-date complication and a winding automatic movement.",
    rating: 4.7,
    reviews: 11,
    dateAdded: 5,
  },
  {
    id: "hamilton-ventura",
    slug: "hamilton-ventura-electric",
    sku: "H24411732",
    brand: "Hamilton",
    brandSlug: "hamilton",
    name: "Ventura Classic Electric | H24411732",
    price: 120000,
    compareAt: 128000,
    image: "/images/products/img-31.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Rubber",
    dial: "Black",
    movement: "Quartz",
    caseSize: "32mm",
    waterResistance: "5 ATM",
    description:
      "The shield-shaped icon Elvis wore — a trapezoid of black and steel that still looks like the future decades after it first appeared.",
    rating: 4.6,
    reviews: 9,
    dateAdded: 4,
  },
  // ---- Fossil (3) ----
  {
    id: "fossil-machine-chronograph",
    slug: "fossil-machine-chronograph-fs6098",
    sku: "FS6098",
    brand: "Fossil",
    brandSlug: "fossil",
    name: "Machine Chronograph Black | FS6098",
    price: 28500,
    compareAt: 34000,
    image: "/images/products/product-07.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Steel",
    dial: "Black",
    movement: "Quartz",
    caseSize: "44mm",
    waterResistance: "5 ATM",
    description:
      "An everyday statement. Bold chronograph layout, brushed stainless bracelet and a dark dial that anchors any look from boardroom to weekend.",
    rating: 4.6,
    reviews: 18,
    dateAdded: 3,
  },
  {
    id: "fossil-townsman",
    slug: "fossil-townsman-automatic",
    sku: "ME3101",
    brand: "Fossil",
    brandSlug: "fossil",
    name: "Townsman Automatic | ME3101",
    price: 32500,
    compareAt: 36000,
    image: "/images/products/img-32.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Leather",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "44mm",
    waterResistance: "5 ATM",
    description:
      "An exhibition caseback that shows off the automatic movement, a sunray blue dial and the quiet confidence of the Townsman.",
    rating: 4.6,
    reviews: 13,
    dateAdded: 2,
  },
  {
    id: "fossil-grant-chronograph",
    slug: "fossil-grant-chronograph",
    sku: "FS5158",
    brand: "Fossil",
    brandSlug: "fossil",
    name: "Grant Chronograph | FS5158",
    price: 26500,
    compareAt: 29500,
    image: "/images/products/img-33.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Leather",
    dial: "White",
    movement: "Quartz",
    caseSize: "44mm",
    waterResistance: "5 ATM",
    description:
      "The Grant channels mid-century Americana — a clean white dial, brown leather strap and a chronograph layout that belongs at the office.",
    rating: 4.5,
    reviews: 21,
    dateAdded: 1,
  },
  // ---- Emporio Armani (3) ----
  {
    id: "emporio-armani-luigi",
    slug: "emporio-armani-luigi-ar1828",
    sku: "AR1828",
    brand: "Emporio Armani",
    brandSlug: "emporio-armani",
    name: "Luigi Black Dial | AR1828",
    price: 38500,
    compareAt: 43000,
    image: "/images/products/product-09.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "Black",
    movement: "Quartz",
    caseSize: "43mm",
    waterResistance: "5 ATM",
    description:
      "Minimal Milanese flair. A refined black dial, sleek indices and Emporio Armani's iconic logo make the Luigi the cleanest-dressed watch in its class.",
    rating: 4.6,
    reviews: 14,
    dateAdded: 12,
  },
  {
    id: "emporio-armani-chrono-classic",
    slug: "emporio-armani-chronograph-classic-ar2430",
    sku: "AR2430",
    brand: "Emporio Armani",
    brandSlug: "emporio-armani",
    name: "Chronograph Classic | AR2430",
    price: 42500,
    compareAt: 47000,
    image: "/images/products/img-34.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Leather",
    dial: "Black",
    movement: "Quartz",
    caseSize: "44mm",
    waterResistance: "5 ATM",
    description:
      "A three-subdial chronograph on a black leather strap. EA's logo and clean numerals keep it sharp without shouting.",
    rating: 4.5,
    reviews: 10,
    dateAdded: 11,
  },
  {
    id: "emporio-armani-classico",
    slug: "emporio-armani-classico-ar1952",
    sku: "AR1952",
    brand: "Emporio Armani",
    brandSlug: "emporio-armani",
    name: "Classico Steel | AR1952",
    price: 38500,
    compareAt: 42000,
    image: "/images/products/img-35.jpg",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "White",
    movement: "Quartz",
    caseSize: "42mm",
    waterResistance: "5 ATM",
    description:
      "The Classico strips the dial back to the essentials — indices, hands and the eagle logo on a polished steel bracelet.",
    rating: 4.6,
    reviews: 8,
    dateAdded: 10,
  },
  // ---- SEVENFRIDAY (3) ----
  {
    id: "sevenfriday-p3-racer",
    slug: "sevenfriday-p3-02-racer",
    sku: "P3-02-RACER",
    brand: "SEVENFRIDAY",
    brandSlug: "sevenfriday",
    name: "P3-02 Racer Chronograph",
    price: 125000,
    compareAt: 142000,
    image: "/images/products/product-05.jpg",
    badge: "LIMITED",
    gender: "Men",
    category: "Chronograph",
    strap: "Leather",
    dial: "Black",
    movement: "Automatic",
    caseSize: "47mm",
    waterResistance: "10 ATM",
    description:
      "An industrial-chic automotive icon. Square sapphire crystal, skeleton dial and an automatic movement finished with SEVENFRIDAY's unmistakable mechanical art.",
    rating: 4.9,
    reviews: 9,
    dateAdded: 14,
  },
  {
    id: "sevenfriday-p1-01",
    slug: "sevenfriday-p1-01-crusader",
    sku: "P1-01-CRUSADER",
    brand: "SEVENFRIDAY",
    brandSlug: "sevenfriday",
    name: "P1-01 Crusader",
    price: 132000,
    compareAt: 145000,
    image: "/images/products/img-36.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Rubber",
    dial: "Black",
    movement: "Automatic",
    caseSize: "47mm",
    waterResistance: "10 ATM",
    description:
      "The original that started it all. A multi-layered dial and 47mm square case that turns heads in any room — SEVENFRIDAY's industrial art in motion.",
    rating: 4.8,
    reviews: 6,
    dateAdded: 13,
  },
  {
    id: "sevenfriday-v3-01",
    slug: "sevenfriday-v3-01-cobra",
    sku: "V3-01-COBRA",
    brand: "SEVENFRIDAY",
    brandSlug: "sevenfriday",
    name: "V3-01 Cobra",
    price: 148000,
    compareAt: 160000,
    image: "/images/products/img-37.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Rubber",
    dial: "White",
    movement: "Automatic",
    caseSize: "47.6mm",
    waterResistance: "10 ATM",
    description:
      "The white-dial Cobra brings a lighter, brighter take to the square watch — still unmistakably SEVENFRIDAY, now with a cleaner face.",
    rating: 4.8,
    reviews: 5,
    dateAdded: 13,
  },
  // ---- Zeyron (3, house brand) ----
  {
    id: "zeyron-origin",
    slug: "zeyron-origin-eastern-numeral-graphite-zof-2501",
    sku: "ZOF-2501-BLK",
    brand: "Zeyron",
    brandSlug: "zeyron",
    name: "Origin Eastern Numeral Graphite | ZOF 2501",
    price: 14500,
    compareAt: 21000,
    image: "/images/products/product-01.jpg",
    badge: "NEW",
    gender: "Men",
    category: "Dress",
    strap: "Steel",
    dial: "Black",
    movement: "Automatic",
    caseSize: "41mm",
    waterResistance: "5 ATM",
    description:
      "A graphite dial with eastern numerals, wrapped in a brushed steel case. The Origin is Zeyron's quiet statement of intent — an automatic dress watch built for the city.",
    rating: 4.9,
    reviews: 28,
    dateAdded: 16,
  },
  {
    id: "zeyron-rosabella",
    slug: "zeyron-rosabella-eastern-numeral-aqua-zr-2563",
    sku: "ZR-2563-AQUA",
    brand: "Zeyron",
    brandSlug: "zeyron",
    name: "Rosabella Eastern Numeral Aqua | ZR 2563",
    price: 14500,
    compareAt: 21500,
    image: "/images/products/product-12.jpg",
    badge: "NEW",
    gender: "Ladies",
    category: "Dress",
    strap: "Steel",
    dial: "Blue",
    movement: "Quartz",
    caseSize: "32mm",
    waterResistance: "3 ATM",
    description:
      "Delicate and distinct. The Rosabella dresses eastern numerals in soft aqua tones with a slim steel case made for every day.",
    rating: 4.9,
    reviews: 31,
    dateAdded: 15,
  },
  {
    id: "zeyron-aviator",
    slug: "zeyron-aviator-42-chronograph",
    sku: "ZA-4201-GRY",
    brand: "Zeyron",
    brandSlug: "zeyron",
    name: "Aviator 42 Chronograph | ZA 4201",
    price: 18500,
    compareAt: 24000,
    image: "/images/products/img-18.jpg",
    gender: "Men",
    category: "Chronograph",
    strap: "Leather",
    dial: "Black",
    movement: "Quartz",
    caseSize: "42mm",
    waterResistance: "5 ATM",
    description:
      "A pilot-inspired chronograph with bold numerals and a sunray dial. The Aviator brings cockpit style to an everyday price.",
    rating: 4.7,
    reviews: 17,
    dateAdded: 14,
  },
  // ---- Couple sets (2) ----
  {
    id: "zeyron-origin-couple-aqua",
    slug: "zeyron-origin-couple-aqua-soft",
    sku: "CREED-CPL-002",
    brand: "Zeyron",
    brandSlug: "zeyron",
    name: "Origin & Rosabella Couple Set — Aqua",
    price: 29000,
    compareAt: 42000,
    image: "/images/products/product-01.jpg",
    gender: "Couple",
    category: "Couple",
    strap: "Steel",
    dial: "Blue",
    movement: "Automatic",
    caseSize: "37mm",
    waterResistance: "5 ATM",
    description:
      "The Origin for him and the Rosabella for her — an automatic couple set in matching aqua tones, finished in a premium dual gift box.",
    rating: 4.8,
    reviews: 13,
    dateAdded: 12,
  },
  {
    id: "casio-couple-mtp-ltp",
    slug: "casio-couple-watch-mtp-ltp-v007",
    sku: "CREED-CPL-001",
    brand: "Casio",
    brandSlug: "casio",
    name: "Couple Watch Set — Silver | MTP/LTP V007",
    price: 8500,
    compareAt: 10500,
    image: "/images/products/product-12.jpg",
    gender: "Couple",
    category: "Couple",
    strap: "Leather",
    dial: "White",
    movement: "Quartz",
    caseSize: "34mm",
    waterResistance: "3 ATM",
    description:
      "One pair, two timepieces. A classic silver couple set in elegant packaging — the perfect gift for two people who like to move in time together.",
    rating: 4.7,
    reviews: 24,
    dateAdded: 11,
  },
];

export function slugifyBrand(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function formatTk(n: number): string {
  return `Tk ${n.toLocaleString("en-IN")}`;
}

export function productHref(product: Product): string {
  return `/product/${product.slug}`;
}

export function galleryFor(product: Product): string[] {
  const others = products.filter((p) => p.id !== product.id).slice(0, 2);
  return [product.image, ...others.map((p) => p.image)];
}

export const priceRanges = [
  { label: "Under Tk 10,000", min: 0, max: 10000 },
  { label: "Tk 10,000 – 50,000", min: 10000, max: 50000 },
  { label: "Tk 50,000 – 1,00,000", min: 50000, max: 100000 },
  { label: "Over Tk 1,00,000", min: 100000, max: Infinity },
];

export function uniqueBrands(list: Product[]): string[] {
  return [...new Set(list.map((p) => p.brand))].sort();
}

export function uniqueOptions(
  list: Product[],
  key: "strap" | "dial" | "gender",
): string[] {
  return [...new Set(list.map((p) => p[key]))].sort();
}

export const brands = [
  "SEVENFRIDAY",
  "Seiko",
  "Casio",
  "Citizen",
  "Orient",
  "Tissot",
  "Longines",
  "Rado",
  "Hamilton",
  "Fossil",
  "Emporio Armani",
  "Zeyron",
];
