[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PRIVATE_BYPASS_SINGLE_BUILD = "true"
  AWS_LAMBDA_JS_RUNTIME = "nodejs24.x"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
